### ISSUE TITLE
Face Error on Ubuntu 16.04 when use such module

### ISSUE THREAD

**Issue by sophy228** [bunkahle/PILasOPENCV#3]
raceback (most recent call last):
  File "generateTrainSet.py", line 8, in <module>
    import PILasOPENCV as Image
  File "/home/zmwu/work2/ML/venv/lib/python3.5/site-packages/PILasOPENCV.py", line 12, in <module>
    from ctypes.wintypes import WORD, DWORD, LONG
  File "/usr/lib/python3.5/ctypes/wintypes.py", line 20, in <module>
    class VARIANT_BOOL(ctypes._SimpleCData):
ValueError: _type_ 'v' not supported

Can't work on Linux?

**Comment by bunkahle** [comment]
Hi Sophy,

I fixed this issue by catching the exception you mentioned. Try to install the latest version by getting it from github or installing it via pip: pip install PILasOPENCV==1.9
So unfortunaltey ImageGrab.grabclipboard() will not work on your platform but the others should work fine.

**Comment by bunkahle** [comment]
Ups, seem not solved the latter case by not catching the exception on import of ctypes datatypes. Solved this so it should work now. Try to install the latest version 2.0 by installing it with PIP install PILasOPENCV==2.0 or download it from github.

**Comment by sophy228** [comment]
Thanks very much， no issues now
